### ISSUE TITLE
Error on first install

### ISSUE THREAD

**Issue by danst0** [tigattack/ansible-role-mergerfs#20]
Hi,

I get the following error when starting on a clean ubuntu 24.04 Server.

Daniel

[tigattack.mergerfs : Install mergerfs package with apt] *****************************************************************************************************************************
fatal: [cassius4]: FAILED! => {"changed": false, "msg": "Unable to install package: E:read, still have 8 to read but none left"}

**Comment by danst0** [comment]
It did work, after setting the method to package_manager instead of GitHub. However, installing a deb from GitHub seems not to work with this command.

**Comment by tigattack** [comment]
Thanks for letting me know. I'm unable to replicate this in tests. Could you let me know:
* If you've defined a `mergerfs_version` and, if so, to what value
* Which version of Debian you're running this against

**Comment by danst0** [comment]
Hi,

these are the versions:

---- no version on mergerfs_version


----
running ubuntu 24.10

---- settings for mergerfs
```
mergerfs_install_mode: package_manager
merger_fs_enable: true
mergerfs_mounts:
  - path: "{{ mfs_pool }}"
    branches:
      - "{{ mfs_ssd }}"
 #     - "{{ mfs_ssd2 }}"
      - "{{ mfs_disk1 }}"
      
    options: allow_other,use_ino,category.create=ff
```



----  Ansible on my control host
```
ansible-playbook [core 2.16.7]
  config file = /Users/danst/ansible/ansible.cfg
  configured module search path = ['/Users/danst/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/danst/ansible/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/danst/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/danst/ansible/.venv/bin/ansible-playbook
  python version = 3.12.9 (main, Feb  4 2025, 14:38:38) [Clang 16.0.0 (clang-1600.0.26.6)] (/Users/danst/ansible/.venv/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True

```
